---
kind: pipeline
type: docker
name: default

steps:

- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./node_modules

- name: website
  image: node:18
  commands:
  - apt-get update && apt-get install rsync -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
  - mkdir -p $HOME/.ssh
  - ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
  - echo "$GITHUB_PRIVATE_KEY" > "$HOME/.ssh/id_rsa"
  - chmod 0600 $HOME/.ssh/id_rsa
  - yarn install --frozen-lockfile
  - npm run crowdin:sync
  - npm run deploy
  environment:
    USE_SSH: true
    GIT_USER: $DRONE_COMMIT_AUTHOR
    NODE_OPTIONS: "--max_old_space_size=12288"
    CROWDIN_PERSONAL_TOKEN:
      from_secret: "CROWDIN_PERSONAL_TOKEN"
    GITHUB_PRIVATE_KEY:
      from_secret: "git_deploy_private_key"
    REACT_APP_DOMAIN:
      from_secret: "REACT_APP_DOMAIN"
    REACT_APP_EVENTS_API:
      from_secret: "REACT_APP_EVENTS_API"
    REACT_APP_CLIENT_ID:
      from_secret: "REACT_APP_CLIENT_ID"
    REACT_APP_TENANT_ID:
      from_secret: "REACT_APP_TENANT_ID"
    REACT_APP_API_URI:
      from_secret: "REACT_APP_API_URI"
    REACT_APP_UMAMI_SRC:
      from_secret: "REACT_APP_UMAMI_SRC"
    REACT_APP_UMAMI_ID:
      from_secret: "REACT_APP_UMAMI_ID"
  when:
    event:
      include:
      - push
      - pull_request

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./node_modules

- name: notify
  image: plugins/webhook
  settings:
    urls:
      from_secret: NODE_RED_WEBHOOK
  when:
    status:
    - success
    - failure
volumes:
  - name: cache
    host: 
      path: /var/lib/dokku/data/storage/hfr-drone-runner/cache

trigger:
  branch:
  - main
  event:
    exclude:
    - pull_reques